### ISSUE TITLE
All requests.get and .post requests must always have timeouts

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener-binary-transformers-and-extractors#12]
This line shows a request.get that doesn't have a timeout parameter. Can you grep the code and check that there aren't any other instances?

https://github.com/freelawproject/courtlistener-binary-transformers-and-extractors/blob/a44afceb9d12c90df3cc986d4425bce3b4a29055/src/server.py#L164

Thank you.

**Comment by flooie** [comment]
Resolved with latest PR, closing
