### ISSUE TITLE
ResourceWarnings cont.

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener-binary-transformers-and-extractors#18]
```ResourceWarning: Enable tracemalloc to get the object allocation traceback```

57 Resource Warnings appeared after the switch to py3.8.  We had the same issue in the switch to python 3 for CL.  

```
ResourceWarning: Enable tracemalloc to get the object allocation traceback
13
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/unittest/case.py:630: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/var/run/docker.sock>
14```

**Comment by mlissner** [comment]
Gonna have a good time knocking these out. Man.

**Comment by flooie** [comment]
@mlissner - It's my new favorite hobby.

**Comment by flooie** [comment]
This appears to be caused by the docker sdk client - being created to start the docker clients in the docker sdk that starts our containers in tests without closing the docker clients.  A simple client.close() in setup and teardown resolves this issue.
